FROM node:lts-alpine3.16

# update and install dependency
RUN apk update && apk upgrade
RUN apk add git g++ make libpng-dev nasm yarn

RUN yarn global add cross-env

# Cache and Install dependencies
COPY package.json .
COPY yarn.lock .
RUN yarn install --production=false

# Copy app files
COPY . .

# Build the app
COPY scripts/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]